services:
  - type: web
    name: sewjo-client
    runtime: docker
    plan: free
    rootDir: "./client"
    dockerfilePath: "./client/Dockerfile"
    envVars:
      - key: NEXT_PUBLIC_BACKEND_URL
        value: http://localhost:8080
      
  - type: web
    name: sewjo-server
    runtime: docker
    plan: free
    rootDir: "./server/main"
    dockerfilePath: "./server/main/Dockerfile"
    envVars:
      - key: CLIENT_URL
        value: http://localhost:3000
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: SUPABASE_EMAIL
        sync: false
      - key: SUPABASE_PASSWORD
        sync: false
  - type: web
    name: sewjo-ocr
    runtime: docker
    plan: free
    rootDir: "./services/ocr"
    dockerfilePath: "./services/ocr/Dockerfile"

